//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poliklinik.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Add
    {
        public int ID { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public System.DateTime Date { get; set; }
        public string TypeProcedure { get; set; }
        public string image { get; set; }
    }
}
